---
name: JSON-Util
version: 0.03
author:
  - 'Jozef Kutej <jkutej@cpan.org>'
abstract: encode/decode with artificial stupidity
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  File::Temp: 0
  Test::Differences: 0
  Test::More: 0
requires:
  Carp: 0
  IO::Any: 0
  JSON::XS: 0
  Scalar::Util: 0
configure_requires:
  Module::Build: 0.35
provides:
  JSON::Util:
    file: lib/JSON/Util.pm
    version: 0.03
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
