---
abstract: 'easy and portable encode/decode of JSON'
author:
  - 'Jozef Kutej <jkutej@cpan.org>'
build_requires:
  File::Temp: 0
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JSON-Util
provides:
  JSON::Util:
    file: lib/JSON/Util.pm
    version: 0.05
requires:
  Carp: 0
  IO::Any: 0
  JSON::XS: 0
  Scalar::Util: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
